### ISSUE TITLE
UI - Cannot set UI to manage network settings

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/dnssafety#217]
```
Traceback (most recent call last):
  File "/opt/dnssafety-ui/var/console/node/views/network.py", line 89, in form_valid
    NetAdvanced.objects.first()
  File "/opt/dnssafety-ui/var/console/node/blogic.py", line 47, in generate
    return self.generate_linux_ubuntu18(devices, advanced)
  File "/opt/dnssafety-ui/var/console/node/blogic.py", line 137, in generate_linux_ubuntu18
    NetPlanNetworkSettingsGenerator().generate(data)
  File "/opt/dnssafety-ui/var/console/_domain/node/netgen_netplan.py", line 29, in generate
    with tempfile.NamedTemporaryFile(prefix=prefix, dir=folder, delete=True) as temp:
  File "/usr/lib/python3.6/tempfile.py", line 690, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.6/tempfile.py", line 401, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/dnssafety-ui/etc/node/etc_netplan_yml.1lrq07bt'
```

**Comment by ra-at-diladele-com** [comment]
It works now.
