### ISSUE TITLE
Restore fails only from version 0.8 (from version 0.7 works normally)

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/dnssafety#316]
```
Cannot restore configuration, errors: name 'value' is not defined

Traceback (most recent call last):
  File "/opt/dnssafety-ui/var/console/node/views/backup.py", line 150, in form_valid
    self.do_action(form)
  File "/opt/dnssafety-ui/var/console/node/views/backup.py", line 190, in do_action
    self.do_import(form, unpack_dir, version_core)
  File "/opt/dnssafety-ui/var/console/node/views/backup.py", line 270, in do_import
    os.path.join(unpack_dir, "var.dnssafety-ui")
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/dnssafety-ui/var/console/frame/models.py", line 216, in upgrade
    SafetyUpgrader(self.major, self.minor).upgrade(etc_dir, db_dump)
  File "/opt/dnssafety-ui/var/console/safety/upgrader.py", line 1036, in upgrade
    ForwardersImporter().upgrade(data["forwarders"])
  File "/opt/dnssafety-ui/var/console/safety/upgrader.py", line 890, in upgrade
    self.upgrade_public(o, data["public"])
  File "/opt/dnssafety-ui/var/console/safety/upgrader.py", line 913, in upgrade_public
    self.upgrade_public_custom(o, data["custom"])
  File "/opt/dnssafety-ui/var/console/safety/upgrader.py", line 926, in upgrade_public_custom
    o.public_custom_conn   = o.conn_int(data.get("conn", []))
  File "/opt/dnssafety-ui/var/console/safety/models.py", line 209, in conn_int
    assert(type(value) == list)
NameError: name 'value' is not defined
```

**Comment by ra-at-diladele-com** [comment]
Fixed. Seems to work just fine now.
