### ISSUE TITLE
/opt/dnssafety-ui/var/console/utils.py --network=debian10 does not work

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/dnssafety#344]
Error:
```
Traceback (most recent call last):
  File "/opt/dnssafety-ui/var/console/node/views/network.py", line 89, in form_valid
    NetAdvanced.objects.first()
  File "/opt/dnssafety-ui/var/console/node/blogic.py", line 39, in generate
    return self.generate_linux_ubuntu16(devices, advanced)
  File "/opt/dnssafety-ui/var/console/node/blogic.py", line 142, in generate_linux_ubuntu16
    self.generate_linux_ubuntu16_manual(advanced.manual_text)
  File "/opt/dnssafety-ui/var/console/node/blogic.py", line 185, in 
generate_linux_ubuntu16_manual
    with open(new_file, "w") as fout:
FileNotFoundError: [Errno 2] No such file or directory: 
    '/opt/dnssafety-ui/etc/node/etc_network_interfaces.manual.new'
```

**Comment by ra-at-diladele-com** [comment]
See the feature-network-debian10 branch and try to debug. Especially DNS search and DNS servers settings. I got the impression it might work the same on Debian 10 as on Ubuntu 16. And it is good.

**Comment by ra-at-diladele-com** [comment]
Nope, on Debian 10 we must write DNS servers to the /etc/resolv.conf. Need to implement.

**Comment by ra-at-diladele-com** [comment]
Done, seems to work.
