### ISSUE TITLE
definitions.py cannot read proxy settings from network.ini

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/dnssafety#404]
```
2019-09-17 06:25:02,276 Error     : No section: 'proxy'
2019-09-17 06:25:02,291 Traceback : Traceback (most recent call last):
  File "/opt/dnssafety/bin/definitions.py", line 39, in update
    u.update(tmp_dir)
  File "/opt/dnssafety/bin/daemon/updater.py", line 36, in update
    self.update_definition(folder, definition)
  File "/opt/dnssafety/bin/daemon/updater.py", line 50, in update_definition
    u.update(parent_folder)
  File "/opt/dnssafety/bin/daemon/hosts.py", line 36, in update
    data = self.retrieve(folder)
  File "/opt/dnssafety/bin/daemon/hosts.py", line 63, in retrieve
    d = Downloader()
  File "/opt/dnssafety/bin/daemon/download.py", line 18, in __init__
    if int(c.get('proxy', 'enable')) != 0:
  File "/usr/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'proxy'
```

**Comment by ra-at-diladele-com** [comment]
Fixed, need to test.
