### ISSUE TITLE
Doesnt installed on Ubuntu 20.04

### ISSUE THREAD

**Issue by asterriya** [diladele/dnssafety#437]
That's what I got on the last step when trying to install dnsfilter gui and also Apache2 doesnt work too

2020-10-03 23:21:40,730 Resetting network configuration to 'ubuntu18' ...
Traceback (most recent call last):
  File "/opt/dnssafety-ui/var/console/utils.py", line 99, in <module>
    main()
  File "/opt/dnssafety-ui/var/console/utils.py", line 93, in main
    process_args(args)
  File "/opt/dnssafety-ui/var/console/utils.py", line 74, in process_args
    process_network(args.network)
  File "/opt/dnssafety-ui/var/console/utils.py", line 57, in process_network
    NetworkDeviceSyncer().reread_from_system(force_sync)
  File "/opt/dnssafety-ui/var/console/node/blogic.py", line 255, in reread_from_system
    actual = NetDeviceEnumerator().enumerate()
  File "/opt/dnssafety-ui/var/console/_domain/node/network.py", line 26, in enumerate
    return self.enumerate_linux()
  File "/opt/dnssafety-ui/var/console/_domain/node/network.py", line 78, in enumerate_linux
    nics[name] = self.enumerate_linux_device(name)
  File "/opt/dnssafety-ui/var/console/_domain/node/network.py", line 116, in enumerate_linux_device
    NetPlanIpParser().fill(device)
  File "/opt/dnssafety-ui/var/console/_domain/node/netaddr.py", line 28, in fill
    raise Exception("Cannot file default netplan file in '%s'" % filename)
Exception: Cannot file default netplan file in '/etc/netplan/50-cloud-init.yaml'

I try to use Debian 9/10 and Ubuntu 18 but still doesnt install properly on the stage 2 (dngfilter gui and apache2 service is not working). Try even on the fresh system but the same error's.

**Comment by ra-at-diladele-com** [comment]
The code assumes it is run on Ubuntu 18 - for Debian 10 it shall be like:

Resetting network configuration to 'debian10'

I will take a look anyway when we start making 0.17 to support Ubuntu 20.

**Comment by asterriya** [comment]
It doesnt work on debia9/10 too. I try many times and even on fresh system.

**Comment by ra-at-diladele-com** [comment]
Version 1.0 will only run on Debian 11.
