### ISSUE TITLE
Unable to restore 0.16 backup file

### ISSUE THREAD

**Issue by snapprhead** [diladele/dnssafety#485]
dnssafety_backup_0.16.0.F48A_2022_09_28.zip

Warning!
Cannot restore configuration, errors: Unsupported minor number in version 0.16

Traceback (most recent call last):
  File "/opt/dnssafety-ui/var/console/node/views/backup.py", line 149, in form_valid
    self.do_action(form)
  File "/opt/dnssafety-ui/var/console/node/views/backup.py", line 189, in do_action
    self.do_import(form, unpack_dir, version_core)
  File "/opt/dnssafety-ui/var/console/node/views/backup.py", line 266, in do_import
    upgrader = Upgrader(test_only, version2)
  File "/opt/dnssafety-ui/var/console/frame/models.py", line 178, in __init__
    raise Exception("Unsupported minor number in version %s" % version)
Exception: Unsupported minor number in version 0.16

**Comment by ra-at-diladele-com** [comment]
In /opt/dnssafety-ui/var/console/frame/models.py  line 177, add the ,"16" to the array of versions to upgrade from, so that it looks like:

```
if minor not in ["0", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16"]:
```

Reboot the box and try to import zip file from 0.16 again.

**Comment by musmank1** [comment]
its working

**Comment by Damiortiz** [comment]
Funciono perfecto! Muchas gracias Diladele!
