### ISSUE TITLE
dashboard / tab dns server - does not work

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/dnssafety#496]
```
Traceback (most recent call last):
  File "/opt/dnssafety-ui/var/console/node/views/dash.py", line 105, in get
    df = NowData().dataframe()
         ^^^^^^^^^
  File "/opt/dnssafety-ui/var/console/_domain/traffic/dash/dns.py", line 25, in __init__
    c.collect()
  File "/opt/dnssafety-ui/var/console/_domain/traffic/collect/collector_now.py", line 36, in collect
    entries = self.read_entries(where, lines_limit)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/dnssafety-ui/var/console/_domain/traffic/collect/collector_now.py", line 70, in read_entries
    raise Exception("Access log '%s' does not exist, please ensure the dsdnsd daemon is up and running!" % self.access_log)
Exception: Access log '/opt/dnssafety/var/log/access.log' does not exist, please ensure the dsdnsd daemon is up and running!
```

**Comment by ra-at-diladele-com** [comment]
Rephrased the error message to tell that if no one is using the DNS server then nothing will be shown in the statistics.
