### ISSUE TITLE
cannot set timezone (needs to be run in venv)

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/dnssafety#497]
```
ERROR: Cannot set timezone to 'Europe/Amsterdam'. Error: 1 (stdout: , stderr: Traceback (most recent call last): File "/opt/dnssafety-ui/bin/timezone.py", line 5, in <module> import pytz ModuleNotFoundError: No module named 'pytz' ) Traceback (most recent call last): File "/opt/dnssafety-ui/var/console/node/views/timezone.py", line 60, in post raise Exception("Cannot set timezone to '%s'. Error: %d (stdout: %s, stderr: %s)" % (timezone, ret, stdout, stderr)) Exception: Cannot set timezone to 'Europe/Amsterdam'. Error: 1 (stdout: , stderr: Traceback (most recent call last): File "/opt/dnssafety-ui/bin/timezone.py", line 5, in <module> import pytz ModuleNotFoundError: No module named 'pytz' ) 
```

**Comment by ra-at-diladele-com** [comment]
Decided to drop pytz check and only use system python libraries.
